### ISSUE TITLE
Sound Delay Gets Bad While Frontend Developing

### ISSUE THREAD

**Issue by tomiyee** [JoshWannaPaas/eight-bar-line#42]
The sound of the notes begins to get more and more delayed as the browser is not loading during the frontend development.

**Comment by JoshWannaPaas** [comment]
I believe I found out how to reproduce the lag, but not why it happens.
The lag happens when you create an ensemble through the interface. Going into an ensemble this way makes the sound play way behind. However, if you refresh the page or navigate to a room using a link instead, there is no sound delay.

**Comment by tomiyee** [comment]
I'll investigate a solution for the audio lag once PR https://github.com/JoshWannaPaas/eight-bar-line/pull/52 goes into `main`.

**Comment by JoshWannaPaas** [comment]
Mostly fixed in #64
